export let tasks = [
  {
    start: new Date(2020, 1, 1),
    end: new Date(2020, 1, 2),
    name: 'first task',
    id: 'Task 0',
    type: 'task',
    progress: 45,
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    start: new Date(2020, 1, 1),
    end: new Date(2020, 1, 5),
    name: 'second task',
    id: 'Task 0',
    type: 'task',
    progress: 90,
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    start: new Date(2020, 1, 6),
    end: new Date(2020, 1, 12),
    name: 'task',
    id: 'Task 0',
    type: 'task',
    progress: 80,
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    start: new Date(2020, 1, 1),
    end: new Date(2020, 1, 4),
    name: 'task',
    id: 'Task 0',
    type: 'task',
    progress: 70,
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    start: new Date(2020, 1, 1),
    end: new Date(2020, 1, 10),
    name: 'task',
    id: 'Task 0',
    type: 'task',
    progress: 90,
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
  {
    start: new Date(2020, 1, 4),
    end: new Date(2020, 1, 10),
    name: 'task',
    id: 'Task 0',
    type: 'task',
    progress: 90,
    isDisabled: true,
    styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
  },
];
